eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
server:
  port: 9011
spring:
  application:
    name: education-search
  data:
    solr:
      host: http://www.bwieyjs.com:8080/solr
